name: Build Qt


on:
  push:
    branches:
    - master
    tags:
    - v*


jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container: ubuntu:20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Build
      run: ./build-linux.sh all

    - name: Save
      uses: actions/upload-artifact@v2
      with:
        name: release-linux
        path: archive/*.tar.xz


  build-win:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up MSYS2 PATH
      run: echo ::add-path::C:\msys64\usr\bin\
      shell: pwsh

    - name: Build
      run: ./build-win.sh
      shell: bash --login -eo pipefail "{0}"
      env:
        MSYSTEM: MINGW64
        CHERE_INVOKING: 1
        MSYS2_PATH_TYPE: inherit

    - name: Save
      uses: actions/upload-artifact@v2
      with:
        name: release-win
        path: "C:/msys64/home/a/*.pkg.tar.zst"


  build-osx:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Build
      run: ./build-osx.sh all

    - name: Save
      uses: actions/upload-artifact@v2
      with:
        name: release-osx
        path: archive/*.tar.xz


  release:
    if: startsWith(github.ref, 'refs/tags/')

    needs:
    - build-linux
    - build-win
    - build-osx

    runs-on: ubuntu-20.04
    steps:
    - name: Download
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Generate release notes
      run: ./generate-release-notes.sh > RELEASE.md

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        files:
        - artifacts/release-linux/*.tar.xz
        - artifacts/release-win/*.pkg.tar.zst
        - artifacts/release-osx/*.tar.xz
        body_path: RELEASE.md
