name: Build Qt


on:
  push:
    tags:
    - v*


jobs:
  build-win:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up MSYS2 PATH
      run: echo ::add-path::C:\msys64\usr\bin\
      shell: pwsh

    - name: Build
      run: ./build-win.sh
      shell: bash --login -eo pipefail "{0}"
      env:
        MSYSTEM: MINGW64
        CHERE_INVOKING: 1
        MSYS2_PATH_TYPE: inherit

    - name: Generate release notes
      shell: bash
      run: ./generate-release-notes.sh > RELEASE.md

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        files: ${{ runner.temp }}/msys/msys64/home/a/*.pkg.tar.xz


  build-osx:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: ./build-osx.sh all

    - name: Generate release notes
      run: ./generate-release-notes.sh > RELEASE.md

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        files: archive/*.tar.xz


  build-linux:
    runs-on: ubuntu-18.04
    container: ubuntu:18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: ./build-linux.sh all

    - name: Generate release notes
      run: ./generate-release-notes.sh > RELEASE.md

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        files: archive/*.tar.xz
        body_path: RELEASE.md
